# Generated by Django 5.1.4 on 2025-02-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedidoingrediente',
            name='cantidadIngrediente',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
