# Generated by Django 5.1.4 on 2025-02-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_detallepedidoingrediente_cantidadingrediente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='frecuencia_uso',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
