# Generated by Django 5.0.3 on 2024-11-13 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_pedido_numeropedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente_nombre',
            field=models.CharField(default='Cliente', max_length=100),
        ),
    ]
