# Generated by Django 5.0.3 on 2024-12-11 02:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_pedido_cantidad_remove_pedido_hecho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
