# Generated by Django 5.0.3 on 2024-12-27 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_proveedor_compra_detallecompra_delete_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('ingrediente', 'Ingrediente'), ('general', 'General')], default='general', max_length=20)),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramo'), ('litro', 'Litro'), ('unidad', 'Unidad')], default='unidad', max_length=20)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='detallecompra',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='detallecompra',
            name='es_ingrediente',
        ),
        migrations.RemoveField(
            model_name='detallecompra',
            name='ingrediente',
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.insumo'),
        ),
    ]
