# Generated by Django 5.0.3 on 2024-12-28 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_detallecompra_insumo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='tipo',
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='ingrediente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.ingrediente'),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.insumo'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='unidad_medida',
            field=models.CharField(choices=[('kg', 'Kilogramo'), ('litro', 'Litro'), ('unidad', 'Unidad')], default='unidad', max_length=20),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidad_medida',
            field=models.CharField(choices=[('unidad', 'Unidad')], default='unidad', max_length=20),
        ),
    ]
