# Generated by Django 5.0.3 on 2024-12-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_insumo_tipo_detallecompra_ingrediente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecompra',
            name='insumo',
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='nombre_insumo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
