# Generated by Django 5.1.4 on 2024-12-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_detallecompra_insumo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='categoria',
            field=models.CharField(choices=[('base', 'Base'), ('adicional', 'Adicional')], default='adicional', max_length=20),
        ),
    ]
