# Generated by Django 5.1.4 on 2025-01-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_proveedor_nombre_historialcostoingrediente'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='tipo',
            field=models.CharField(choices=[('ingrediente', 'Ingrediente'), ('insumo', 'Insumo')], default='insumo', max_length=20),
        ),
    ]
