# Generated by Django 5.1.4 on 2025-01-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_detallecompra_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='tipo',
            field=models.CharField(choices=[('ingrediente', 'Ingrediente'), ('insumo', 'Insumo')], max_length=20),
        ),
    ]
