# Generated by Django 5.1.4 on 2025-01-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_detallecompra_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('simple', 'Crepe Simple'), ('doble', 'Crepe Doble'), ('salado', 'Crepe Salado')], default='simple', max_length=10),
        ),
    ]
